import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative overflow-hidden`}
        style={{} as React.CSSProperties}
      >
        <ReactQueryProvider>
          <SidebarProvider defaultOpen>
            <AppSidebar />
            <SidebarInset className="h-full peer-data-[variant=inset]:min-h-[calc(100svh-theme(spacing.4)-var(--header-height))]">
              <SidebarTrigger className="absolute top-0 right-0" />
              <div className="p-4 w-full">{children}</div>
            </SidebarInset>
          </SidebarProvider>
          <Toaster
            position="top-right"
            richColors
            theme="light"
            duration={3000}
          />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
