name: Deploy

on:
  push:
    branches: [main]
    paths:
      - "crm-backend/**"

env:
  IMAGE: ghcr.io/${{ github.repository }}:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN || github.token }}

      - uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/crm-backend
          file: ${{ github.workspace }}/crm-backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
          platforms: linux/amd64

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            set -e
            mkdir -p /opt/crm
            cat > /opt/crm/.env <<'EOF'
            ${{ secrets.ENV_FILE }}
            EOF
            echo ${{ secrets.GHCR_TOKEN || github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ${{ env.IMAGE }}
            docker rm -f crm-server || true
            docker run -d --name crm-server \
              --env-file /opt/crm/.env \
              --network app-net \
              -p 2222:2222 \
              ${{ env.IMAGE }}
            docker image prune -f
